@startuml Diagrama de Clases


class Cliente {
  - id: int
  - nombre: String
  - tipoDocumento: String
  - Documento: String
  - correo: String

  + createCliente()
  + updateCliente()
  + DeleteCliente()
  + getById()
}

class FacturaCliente {
  - numeroFactura: int
  - fecha: Date
  - clienteId: Cliente

  + create()
  + update()
  + delete()
  + getById()
}

class DetalleFactura {
  - id: int
  - cantidad: int
  - productoCodigo: Producto
  - valorBruto: float
  - valorNeto: float
  - valorDescruento: float
  - valorTotal:float
  - facturaClienteId:FacturaCliente
  + create()
  + update()
  + delete()
  + get()
}

class Producto {
  - Id: int
  - codigo: String
  - nombre: String
  - categoria: String
  - valor: float
  
  + create()
  + update()
  + delete()
  + get()
}


class inventario {
  - codigo: int
  - stock : String
  - fechaIngreso: Date
  - valorDescuento: float
  -porcentajeIva: float

  + REgistrarEntrada()
  + update()
  + delete()
  + get()
  
}
class inventarioSalida {
  - id : int
  - codigo: inventario
  - fechaSalida: Date
 

  + REgistrarSalida()
  + update()
  + delete()
  + get()
  
}





Cliente -- FacturaCliente
FacturaCliente o--* DetalleFactura
Proyecto *-- Tareas
Proyecto *-- Objetivos
Proyecto *-- Hitos
RegistroHistorial *-- Proyecto


@enduml